apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong/kong-gateway:3.9
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: "/kong/kong.yml"
          ports:
            - containerPort: 8000
            - containerPort: 8443
          volumeMounts:
            - name: kong-config-volume
              mountPath: /kong
      volumes:
        - name: kong-config-volume
          configMap:
            name: kong-config
