apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-db-less
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/iriteshp/kong-helm-blue-green.git"
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
