apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kong

configMapGenerator:
  - name: kong-config
    behavior: create
    options:
      disableNameSuffixHash: true
    files:
      - services/echo.yaml
      - services/user.yaml

resources:
  - kong-deployment.yaml
  - kong-service.yaml
