apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kong

configMapGenerator:
  - name: kong-config
    files:
      - services/echo.yaml
      - services/user.yaml

resources:
  - kong-configmap.yaml
  - kong-deployment.yaml
  - kong-service.yaml
